# Generated by Django 3.0.2 on 2022-02-22 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Test Bank', max_length=200)),
                ('account_number', models.UUIDField(default=uuid.uuid5)),
                ('account_name', models.CharField(default='Test Account', max_length=200)),
                ('account_type', models.CharField(choices=[('Savings', 'Savings'), ('Credit', 'Credit')], max_length=200)),
                ('balance', models.FloatField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
