# Generated by Django 3.0.2 on 2022-02-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
